### ISSUE TITLE
Add BOM.csv

### ISSUE THREAD

**Issue by Redherring32** [Staacks/wifi-game-boy-cartridge#3]
A BOM in CSV format (Easily created via octopart.com) would simplify the ordering of parts, and would be a preferable addition to the repository. :)

**Comment by Staacks** [comment]
I exported it from the linked Mouser cart and imported it on octopart. Is this the format you are looking for?

[20220126_projektentwurf_jan26_0234_xls.csv](https://github.com/Staacks/wifi-game-boy-cartridge/files/7945444/20220126_projektentwurf_jan26_0234_xls.csv)

**Comment by Redherring32** [comment]
Yes, that will do nicely!
That'll ease ordering parts.

**Comment by Staacks** [comment]
Ok, added it to the repo.
